### ISSUE TITLE
Navigation does not work outside of  month view

### ISSUE THREAD

**Issue by andrewsrs** [dreamRs/toastui#30] opened 2022-11-10 23:14 UTC
The navigation dates show the correct value only for the month view. Is this the intended behavior?
```` r
library(shiny)
library(toastui)

ui <- fluidPage(
    tags$h2("Change calendar view"),
    radioButtons(
        inputId = "view",
        label = "Change view:",
        choices = c("day", "week", "month"),
        inline = TRUE
    ),
    calendarOutput(outputId = "my_calendar")
)

server <- function(input, output, session) {
    output$my_calendar <- renderCalendar({
        calendar(
            view = "day",
            navigation = TRUE,
            navOpts = navigation_options(fmt_date = "MMMM D, YYYY"),
            scheduleView = "allday",
        ) %>%
            cal_schedules(
                title = "Today planning",
                start = Sys.Date(),
                end = Sys.Date(),
                category = "allday"
            )
    })
    observeEvent(input$view,
                 cal_proxy_view("my_calendar", input$view),
                 ignoreInit = TRUE)
}

if (interactive())
    shinyApp(ui, server)
```


`

**Comment by pvictor** [comment] 2022-11-14 08:30
No, that's not the intended behavior, that's fixed in dev version.

Victor

**Comment by andrewsrs** [comment] 2022-11-14 18:06
Yes it is, thanks!

**Closed as completed** 2022-11-15 13:57 UTC
